# lordgasmic/jdk17:1.0.0
# builds the :latest and the version
# docker build -t lordgasmic/jdk17 .
# docker build -t lordgasmic/jdk17:version .
FROM alpine:3.15.4
RUN apk add --no-cache openjdk17
