# lordgasmic/jre17:1.0.0
# builds the :latest and the version
# docker build -t lordgasmic/jre17 .
# docker build -t lordgasmic/jre17:version .
FROM alpine:3.18.2
RUN apk add --no-cache openjdk17-jre-headless
