# lordgasmic/jre14:1.0.0
# builds the :latest and the version
# docker build -t lordgasmic/jre14 .
# docker build -t lordgasmic/jre14:version .
FROM alpine:3.15.4
RUN apk add --no-cache openjdk14-jre-headless
