name: Publish docker on update

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  vars: 
    runs-on: ubuntu-latest
    steps:
      - name: Generate docker tag name
        id: timestamp
        run: echo "tmstmp=lordgasmic/docker" >> "GITHUB_OUTPUT"
        #run: echo "tmstmp=lordgasmic/docker:$(TZ=":America/Detroit" date +%Y%m%d%H%M)" >> "GITHUB_OUTPUT"
        
  build:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo timestamp
        run: echo ${{ steps.timestamp.outputs.tmstmp }}
