name: Publish docker on update

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker tag name
        id: step_one
        run: |
          echo "action_state=party" >> "GITHUB_ENV"
      #- uses: actions/checkout@v2
      - name: echo timestamp
        id: step_two
        run: |
          echo "${{ env.action_state }}"
