name: Publish docker on update

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  vars: 
    runs-on: alpine-latest
    outputs:
      timestamp: ${{ steps.tmstmp.outputs.date }}
    steps:
      - id: tmstmp
        run: echo "::set-output name=date::lordgasmic/docker:$(date +%Y%m%d%H%M)"
        
  build:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo timestamp
        run: echo ${{ needs.vars.outputs.timestamp }}
